// export const FILTER_ALL_SECTIONS = 'FILTER_ALL_SECTIONS'
// export const FILTER_COMPLETED_SECTIONS = 'FILTER_COMPLETED_SECTIONS'
// export const FILTER_NOT_COMPLETED_SECTIONS = 'FILTER_NOT_COMPLETED_SECTIONS'
